# Generated by Django 3.0.8 on 2020-07-31 20:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=50)),
                ('y', models.CharField(max_length=100)),
                ('filename', models.TextField(max_length=50)),
            ],
        ),
    ]
