# Generated by Django 3.0.8 on 2020-07-31 22:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdata',
            name='x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=50),
        ),
    ]
