# Generated by Django 3.0.8 on 2020-08-01 20:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regml', '0002_auto_20200731_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetaData',
            fields=[
                ('project_name', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('col_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), default=list, size=50)),
                ('y_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='regdata',
            name='filename',
        ),
        migrations.AddField(
            model_name='regdata',
            name='project_name',
            field=models.ForeignKey(default='test', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='regml.FileMetaData'),
            preserve_default=False,
        ),
    ]
