# Generated by Django 3.0.8 on 2020-08-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regml', '0003_auto_20200801_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regdata',
            name='project_name',
        ),
        migrations.DeleteModel(
            name='FileMetaData',
        ),
        migrations.DeleteModel(
            name='RegData',
        ),
    ]
