# Generated by Django 3.0.8 on 2020-08-09 18:49

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regml', '0004_auto_20200809_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetaData',
            fields=[
                ('project_name', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 9, 18, 49, 3, 461407))),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metadata RegML',
            },
        ),
        migrations.CreateModel(
            name='RegData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', django.contrib.postgres.fields.jsonb.JSONField()),
                ('project_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='regml.FileMetaData')),
            ],
            options={
                'verbose_name': 'Uploaded Data',
            },
        ),
    ]
