# Generated by Django 3.0.8 on 2020-08-16 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regml', '0005_filemetadata_regdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 18, 17, 29, 990287)),
        ),
        migrations.CreateModel(
            name='ColumnTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.TextField()),
                ('col_type', models.TextField(choices=[('c', 'categorical'), ('n', 'numeric'), ('d', 'date')])),
                ('y', models.BooleanField()),
                ('project_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='regml.FileMetaData')),
            ],
        ),
    ]
