# Generated by Django 3.0.8 on 2020-09-13 20:58

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regml', '0006_auto_20200816_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 20, 58, 45, 232196)),
        ),
        migrations.CreateModel(
            name='DataOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_name', models.TextField(max_length=50)),
                ('output', django.contrib.postgres.fields.jsonb.JSONField()),
                ('project_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='regml.FileMetaData')),
            ],
        ),
    ]
