# Generated by Django 3.0.8 on 2020-09-14 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regml', '0008_auto_20200914_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
